# Generated by Django 5.2.10 on 2026-01-31 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmé'), ('DONE', 'Terminé'), ('CANCELLED', 'Annulé')], default='CONFIRMED', max_length=10),
        ),
    ]
